// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Firebase configured hai — real values hain
  static bool get isConfigured => true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC92jUMB9llVdbc3nBCUvZHd81h2sZ-384',
    appId: '1:778847172278:web:8e96dd5b66f58d12475817',
    messagingSenderId: '778847172278',
    projectId: 'poultrypro-23f36',
    authDomain: 'poultrypro-23f36.firebaseapp.com',
    storageBucket: 'poultrypro-23f36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJJ8AhmkoUd5nYzSKdSk4JGGCNnhneLPY',
    appId: '1:778847172278:android:d2c2516c91da59ac475817',
    messagingSenderId: '778847172278',
    projectId: 'poultrypro-23f36',
    storageBucket: 'poultrypro-23f36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlChplLa4Hx3R9TZyJ6RNtiugqONxS9u0',
    appId: '1:778847172278:ios:2d0486bc683ab2b1475817',
    messagingSenderId: '778847172278',
    projectId: 'poultrypro-23f36',
    storageBucket: 'poultrypro-23f36.firebasestorage.app',
    iosBundleId: 'com.example.poultrypro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlChplLa4Hx3R9TZyJ6RNtiugqONxS9u0',
    appId: '1:778847172278:ios:2d0486bc683ab2b1475817',
    messagingSenderId: '778847172278',
    projectId: 'poultrypro-23f36',
    storageBucket: 'poultrypro-23f36.firebasestorage.app',
    iosBundleId: 'com.example.poultrypro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC92jUMB9llVdbc3nBCUvZHd81h2sZ-384',
    appId: '1:778847172278:web:4a3852d226e897e7475817',
    messagingSenderId: '778847172278',
    projectId: 'poultrypro-23f36',
    authDomain: 'poultrypro-23f36.firebaseapp.com',
    storageBucket: 'poultrypro-23f36.firebasestorage.app',
  );
}
